version: '3.9'

services:

    db:
        image: postgres # latest
        restart: always
        shm_size: 128mb
        environment:
            # other fields are defaults
            POSTGRES_PASSWORD: a1234
            PGPORT: 5430

    adminer:
        image: adminer
        restart: always
        ports:
            - 5430:5430